# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# title: <img src='./img/logo_small.png' /> QuickCheckout. <span style="font-size:20px;line-height:31px;color:#CC66FF;"><strong>Same Store... Better Experience!</strong></span>
#title: <span style="color:#ffffff;">QuickCheckout&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="font-size:14px;line-height:14px;color:#ff8fcf;"><strong>  Same Store... Better Experience!</strong></span>
title: QuickCheckout | Same Store...Better Experience...
subtitle: QC
logo: /img/logo.png

email: quickcheckout@xmarbles.com
author: 
description: Shop from your favourite neighbourhood stores. QuickCheckout is a mobile-first designed solution for online shopping from your neighbourhood store. Order from your favourite neighbourhood store and even discover new ones!
copyright: 'Copyright &copy; 2020 xMarbles. All Rights Reserved.'
credits: 'Credits: Theme design from open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://quickcheckout.in" 
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
theme: minima
plugins: 
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap  
  
social:
  # - title: twitter
  #   url: https://twitter.com/quickcheckout
  - title: facebook
    url: https://www.facebook.com/QuickCheckout-113749100410523
  - title: linkedin
    url: https://www.linkedin.com/company/quickcheckout/
  
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

include:
  - messages